### ISSUE TITLE
yolov5.dll成功编译输出后，无法加载成功

### ISSUE THREAD

**Issue by Softtanck** [Monday-Leo/Yolov5_Tensorrt_Win10#1]
首先非常感谢作者提供的步骤，非常详细！！！
奇怪的是编译可以输出yolov5.dll，但是通过LoadLibrary不能加载成功，通过导出函数查看工具，可以正常看到yolov5.dll的导出函数，看起来像是dll被损坏了一样？可以100%确定yolov5.dll文件是存在的。
![Uploading image.png…]()

**Comment by Softtanck** [comment]
另外补充一下，如果编译exe后，通过命令参数执行是没有任何问题，可以推理出来。

**Comment by Softtanck** [comment]
Addressed from your video. Thanks again.

**Comment by HiRenZeHui** [comment]
我也遇到这个问题了，请问您后来是怎么解决的？
