### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000008

### ISSUE THREAD

**Issue by huaiqi220** [Monday-Leo/Yolov5_Tensorrt_Win10#8]
CUDA11.5
TensorRT 8.2.5.1
编译后使用Yolov5.exe可以直接调用best.engine进行推理，
编译成Yolov5.dll，python3.11 CDLL提示
FileNotFoundError: Could not find module 'C:\Users\zhuzi\Documents\yolov5\build\Release\yolov5.dll' (or one of its dependencies). Try using the full path with constructor syntax.

设置winmod=1提示
OSError: exception: access violation reading 0x0000000000000008

**Comment by Chase2816** [comment]
我遇到了相同的问题，您解决了吗？

**Comment by huaiqi220** [comment]
解决了，但是并没有什么准确的解决方案，win11切换tensorRT，CUDA版本多次还是报这个错。Win10 TensorRT-8.4.3.1 + CUDA 11.7 + cudnn8.6.0.163
Visual Studio 2022 MSVC2017 python3.10 YOLOv5 6.0一次成功，希望可以帮到你。

**Comment by Chase2816** [comment]
win11 tensorrt8.4.1.5 vs2019 cuda11.3 OSError: exception: access violation reading 0x0000000000000008。

**Comment by Chase2816** [comment]
环境：win11-tensorrt8.4.1.5-vs2019-cuda11.3；OSError: exception: access violation reading 0x0000000000000008。
在vs2019中，指定	`std::string engine_name = "./yolov5.engine";`，会使python_trt.py中model_path参数无效，可以成功运行。
分析错误：应该是INIT传入char*参数model_path，没有成功传入或者转换成std::string。
